version: '3'
services:
  mysql:
    image: mortenson/ddl-db
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: password
    ports:
      - '127.0.0.1:0:3306'
    volumes:
      - db:/var/lib/mysql:delegated
    networks:
      - internal
    labels:
      - 'drupaldockerlite=true'
  mailhog:
    image: mailhog/mailhog
    ports:
      - '127.0.0.1:0:8025'
    networks:
      - internal
    labels:
      - 'drupaldockerlite=true'
  php:
    image: mortenson/ddl-web
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST-localhost}
      - DRUPAL_DOCKER_LITE=1
      - SIMPLETEST_DB=mysql://drupal:password@mysql:3306/drupal#simpletest
      - SIMPLETEST_BASE_URL=http://localhost
      - DRUSH_LAUNCHER_FALLBACK=drush8
    labels:
      - 'traefik.enable=true'
      - 'traefik.backend=DDL-${VIRTUAL_HOST-localhost}'
      - 'traefik.frontend.rule=Host:${VIRTUAL_HOST-localhost}'
      - 'traefik.docker.network=ddl_proxy'
      - 'traefik.port=80'
      - 'drupaldockerlite=true'
    ports:
      - '127.0.0.1:0:80'
    volumes:
      - ./code:/var/www/html:cached
      - ./php.ini:/usr/local/etc/php/conf.d/ddl.ini
    depends_on:
      - mysql
      - mailhog
    networks:
      - internal
      - ddl_proxy
volumes:
  db:
networks:
  ddl_proxy:
    external: true
  internal:
    external: false
