#!/bin/bash

if ! type "docker-compose" &> /dev/null; then
  echo "Please install Docker and try running the script again"
  exit 1
fi

DOMAIN=$(docker-compose ps php | grep php | sed 's/_.*//').ddl
URL=http://$(docker-compose port php 80 | sed "s/0.0.0.0/$DOMAIN/")

docker-compose exec php drush --root="/var/www/html/docroot" -l $URL $@
